# Generated by Django 3.2 on 2024-03-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240226_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('VND', 'VND')], default='VND', max_length=255),
        ),
    ]
